FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y iputils-ping

# Install system build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    libffi-dev \
    libssl-dev \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/sync_db.py .
COPY .env .

CMD ["python", "sync_db.py"]
