CREATE TABLE employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  zoho_emp_id VARCHAR(50) NOT NULL UNIQUE,
  biometric_id INT UNIQUE,
  name VARCHAR(255) NOT NULL,
  active TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
